fix: update yml to fix the issue fith acsess4

diff --git a/.gitlab-ci.yml b/.gitlab-ci.yml
--- a/.gitlab-ci.yml
+++ b/.gitlab-ci.yml
@@ -1,19 +1,20 @@
-script:
-  - 'which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )'
-  - eval $(ssh-agent -s)
-  - mkdir -p ~/.ssh
-  - echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_ed25519
-  - chmod 600 ~/.ssh/id_ed25519
-  - ssh-keyscan git.foxminded.ua >> ~/.ssh/known_hosts
-
-  - git remote remove origin
-
-  - git remote add origin git@git.foxminded.ua:foxstudent108179/subscription-bot.git
-  - git fetch origin
-
-  # sanity checks
-  - if [ -z "$RAILWAY_TOKEN" ]; then
-      echo "Missing RAILWAY_TOKEN";
-      exit 1;
-    fi
-  - railway up --service="$SVC_ID"
+deploy-job:
+  image: ghcr.io/railwayapp/cli:latest
+  variables:
+    SVC_ID: my-service
+  script:
+    - which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )
+    - eval $(ssh-agent -s)
+    - mkdir -p ~/.ssh
+    - echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_ed25519
+    - chmod 600 ~/.ssh/id_ed25519
+    - ssh-keyscan git.foxminded.ua >> ~/.ssh/known_hosts
+    - git remote remove origin
+    - git remote add origin git@git.foxminded.ua:foxstudent108179/subscription-bot.git
+    - git fetch origin
+    - |
+      if [ -z "$RAILWAY_TOKEN" ]; then
+        echo "Missing RAILWAY_TOKEN"
+        exit 1
+      fi
+    - railway up --service="$SVC_ID"
